name: cashe_register
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  get: 4.6.5
  flutter: 
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.7+4
  # firebase_core: ^2.11.0
  # cloud_firestore: ^4.6.0
  # firebase_auth: ^4.5.0
  
  

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Gentium
      fonts:
        - asset: assets/fonts/Gentium.ttf